name: Run tests, coverage, and SonarQube analysis

on: [push, pull_request]

jobs:
  test:
    name: Run tests and coverage
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
      # 1. Check out the code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up Python version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      # 4. Run tests with coverage
      - name: Run unit tests with coverage
        run: |
          pytest --cov --cov-branch --cov-report=xml

      # 5. Run mypy type checking
      - name: Run mypy type checking
        run: |
          python -m mypy src/ --strict

      # 6. Upload coverage report to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ajbarea/heartbeat-obstacle-detector

      # 8. Run SonarQube analysis (only on Ubuntu)
      - name: SonarQube Scan
        if: matrix.os == 'ubuntu-latest'
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
